worker_processes  1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

        root "C:/Users/Lenovo/Projects summer-26/Internship Project 1/prompt-manager/prompt-manager-ui/dist";
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/prompts {
            rewrite ^/api/prompts/?$ /prompts break;
            rewrite ^/api/prompts/(.+)$ /prompts/$1 break;
            proxy_pass http://localhost:8000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/reviews {
            rewrite ^/api/reviews/?$ /reviews break;
            rewrite ^/api/reviews/(.+)$ /reviews/$1 break;
            proxy_pass http://localhost:8001;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}