server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/promptdb
    username: postgres
    password: saleha123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true