server:
  port: ${SERVER_PORT:8000}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/promptdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true